name: 'engineerd/configurator'
description: 'Easy and cross-platform action to download, extract, and add to path statically compiled tools.'
author: 'Engineerd'
inputs:
  name:
    description: 'Name your tool will be configured with'
    required: true
  url:
    description: 'URL to download your tool from'
    required: true
  pathInArchive:
    description: 'If the URL points to an archive, this field is required, and points to the path of the tool to configure (relative to the archive root).'
runs:
  using: 'node12'
  main: 'lib/main.js'
