name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1

      - name: "npm install"
        run: npm install

      - name: "npm run build"
        run: npm run build

      - name: "npm run test"
        run: npm run test
        env:
          # this is needed for the tests to execute
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "npm audit"
        run: npm audit
