name: Test rawVersion
on: [push, pull_request]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "npm install"
        run: npm install
      - name: "npm run build"
        run: npm run build
      - uses: ./
        with:
          name: "cue"
          fromGitHubReleases: "true"
          pathInArchive: "cue"
          repo: "cuelang/cue"
          urlTemplate: "https://github.com/cuelang/cue/releases/download/{{version}}/cue_{{version}}_linux_amd64.tar.gz"
          version: "^v0.4.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing
        run: |
          cue --help
